services:
  postgres:
    image: pgvector/pgvector:pg15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: docdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
    command: postgres -c shared_preload_libraries=vector

  #embedder:
    #build: ./embedder
    #ports:
      #- "5001:5001"
    #environment:
      #- MODEL_NAME=all-MiniLM-L6-v2

volumes:
  pgdata:

